### ISSUE TITLE
Testing the SQL Scripts Work

### ISSUE THREAD

**Issue by nelsonic** [dwyl/postgres-history-spike#7]
We've made _excellent_ progress with writing an SQL script that both saves the history of all records in a PostgreSQL database _and_ mirrors the `primary` tables to `_history` tables. #5 🎉 

The code that has been written is not just "spike" (_throw-away proof-of-concept_), it's _useable_! 😮 
There's no reason to _not_ put in the extra effort to make this a production-ready Elixir package that we can start using in our projects and make available for others to do the same. 

# Todo

+ [ ] `CREATE` a small Phoenix project in the `/test` root directory
+ [ ] Run the spike SQL scripts in the Phoenix project
+ [ ] Confirm that the `_history` table is created
+ [ ] `INSERT` data into `primary` table and check that it gets added to the `_history` table
+ [ ] `ALTER` the `primary` table by adding a `new` column.
+ [ ] Confirm that the `new` column added to the `primary` table is mirrored to the `_history` table
+ [ ] `INSERT` another record into the `primary` table _including_ the `new` column. 
+ [ ] _Confirm_ the record was mirrored to the `_history` table.
